export const ET_STRINGS = {
  observationDate: "vaatluse kuupäev",
  refreshMap: "Värskenda kaarti",
  uploadAvatar: "Lae avatar üles",
  sharedManaged: "Hallatakse ühiselt: avatar, eBird speciesCode ja harulduse tase.",
  rarityLabel: "Haruldus",
  rarityNormal: "Tavaline",
  rarityRare: "Haruldane",
  raritySuper: "Väga haruldane",
  rarityMega: "Mega haruldane",
  speciesSettings: "Liigi seaded",
  saveSpeciesSettings: "Salvesta liigi seaded",
  saveSpeciesSettingsOk: "Liigi seaded salvestatud",
  saveSpeciesSettingsLocalOnly: "Salvestatud lokaalselt (pilv ebaõnnestus)",
  KEVAD_RANNE: "Kevadränne",
  FILTER: "Filter...",
  ASUKOHT_PUUDUB: "Asukoht puudub",
  VAATLUSE_KUUPAEV: "vaatluse kuupäev",
  VARSKENDA_KAARTI: "Värskenda kaarti",
  NIMEKIRI: "Nimekiri",
  HARULDUS: "Haruldus",
  NO_LOCATION_YET: "Asukoht puudub",
  DAYS_7: "7 päeva vaatlused",
} as const;
