export const ET_STRINGS = {
  observationDate: "vaatluse kuup\u00e4ev",
  refreshMap: "V\u00e4rskenda kaarti",
  uploadAvatar: "Lae avatar \u00fcles",
  sharedManaged: "Hallatakse \u00fchiselt: avatar, eBird speciesCode ja harulduse tase.",
  rarityLabel: "Haruldus",
  rarityNormal: "Tavaline",
  rarityRare: "Haruldane",
  raritySuper: "V\u00e4ga haruldane",
  rarityMega: "Mega haruldane",
  speciesSettings: "Liigi seaded",
  saveSpeciesSettings: "Salvesta liigi seaded",
  saveSpeciesSettingsOk: "Liigi seaded salvestatud",
  saveSpeciesSettingsLocalOnly: "Salvestatud lokaalselt (pilv eba\u00f5nnestus)",
  KEVAD_RANNE: "Kevadr\u00e4nne",
  FILTER: "Filter...",
  ASUKOHT_PUUDUB: "Asukoht puudub",
  VAATLUSE_KUUPAEV: "vaatluse kuup\u00e4ev",
  VARSKENDA_KAARTI: "V\u00e4rskenda kaarti",
  NIMEKIRI: "Nimekiri",
  HARULDUS: "Haruldus",
  NO_LOCATION_YET: "Asukoht puudub",
  DAYS_7: "7 p\u00e4eva vaatlused",
} as const;