// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-recent-rare-observations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_recent_rare_observations_default = defineTool({
  name: "list_recent_rare_observations",
  title: "List recent rare bird observations",
  description: "List recent rare bird observations relevant to Estonia (from eBird), most recent first. Read-only.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max rows to return (1-100)"),
    country_code: z.string().length(2).optional().describe("ISO country code filter, e.g. EE, LV, FI")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, country_code }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("ebird_rare_observations").select("species_et_name,species_lat_name,species_code,rarity_level,country_code,region,location,lat,lng,obs_date,obs_count,distance_to_ee_km").order("obs_date", { ascending: false }).limit(limit);
    if (country_code) q = q.eq("country_code", country_code.toUpperCase());
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-news.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_recent_news_default = defineTool2({
  name: "list_recent_news",
  title: "List recent birding news",
  description: "List recent birding news items ingested by EstBirding, most recent first. Returns Estonian titles when available. Read-only.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(15).describe("Max items to return (1-50)"),
    source_slug: z2.string().optional().describe("Filter by source slug (e.g. 'eoy')")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, source_slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("news_items_v").select("id,title,title_et,summary,url,published_at,source_slug,source_name,image_url").eq("archived", false).order("published_at", { ascending: false, nullsFirst: false }).limit(limit);
    if (source_slug) q = q.eq("source_slug", source_slug);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-events.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_upcoming_events_default = defineTool3({
  name: "list_upcoming_events",
  title: "List upcoming birding events",
  description: "List upcoming Estonian birding events (talgud, retked, koolitused). Read-only.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("Max events (1-50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabase.from("events").select("*").gte("start_at", nowIso).order("start_at", { ascending: true }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "estbirding-mcp",
  title: "EstBirding",
  version: "0.1.0",
  instructions: "Read-only tools for the EstBirding Estonian birding app: recent rare bird observations near Estonia, birding news, and upcoming events.",
  tools: [list_recent_rare_observations_default, list_recent_news_default, list_upcoming_events_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
