CREATE OR REPLACE VIEW public.news_items_v
WITH (security_invoker = true) AS
 SELECT ni.id,
    ni.source_id,
    ni.title,
    ni.summary,
    ni.content_html,
    ni.url,
    ni.image_url,
    ni.published_at,
    ni.language,
    ni.guid,
    ni.created_at,
    ni.updated_at,
    ni.content_fetched_at,
    ni.content_fetch_error,
    ni.image_url_original,
    ni.source_key,
    ni.external_id,
    ni.body,
    ni.permalink_url,
    ni.fetched_at,
    ni.archived,
    ni.raw_json,
    ni.source_lang,
    ni.translated_title,
    ni.translated_body,
    ni.translation_status,
    ni.translated_at,
    ni.title_et,
    ni.body_et,
    ni.image_cached_url,
    ni.translation_error,
    ni.cached_image_url,
    ni.cached_image_path,
    COALESCE(ns.slug, ni.source_slug, ni.source_id::text, 'legacy'::text) AS source_slug,
    COALESCE(ns.name, ni.source_id::text, 'Legacy'::text) AS source_name,
    COALESCE(ni.cached_image_url, ni.image_url) AS display_image_url,
    ni.title_et_v2,
    ni.body_et_v2
   FROM news_items ni
     LEFT JOIN news_sources ns ON ns.id = ni.source_id;