// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_ANON_KEY, SUPABASE_CONFIG_ERROR, SUPABASE_URL } from '@/config/supabase';

if (import.meta.env.DEV && SUPABASE_CONFIG_ERROR) {
  console.error('[SUPABASE CONFIG ERROR]', SUPABASE_CONFIG_ERROR);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
