// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseAnonKey, getSupabaseUrl, validateSupabaseConfig } from '@/config/supabaseConfig';

const validation = validateSupabaseConfig();

export const supabaseConfigError: string | null = validation.ok ? null : (validation.error ?? 'Supabase config invalid');

if (!validation.ok) {
  const url = getSupabaseUrl();
  const key = getSupabaseAnonKey();
  console.error(
    `[supabase] ${validation.error} ` +
      `(VITE_SUPABASE_URL ${url ? 'set' : 'missing/empty'}, ` +
      `VITE_SUPABASE_ANON_KEY ${key ? 'set' : 'missing/empty'})`,
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function buildConfigErrorProxy(message: string): SupabaseClient<Database> {
  const throwErr = () => {
    throw new Error(`Supabase client unavailable: ${message}`);
  };
  return new Proxy({} as SupabaseClient<Database>, {
    get: throwErr,
    apply: throwErr,
  });
}

export const supabase: SupabaseClient<Database> = validation.ok
  ? createClient<Database>(getSupabaseUrl(), getSupabaseAnonKey(), {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : buildConfigErrorProxy(supabaseConfigError ?? 'config error');
